Рабочая тетрадь №2 Мурдасов И.А./ ИМБО-01-24

№1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np

answer = np.arange(64).reshape(8,8)
for i in range(8):
    check = True
    for j in range(8):
        if i != 0 and check:
            if answer[i-1][j] == 0:
                answer[i][j] = 1
            else:
                answer[i][j] = 0
            check = False
        elif answer[i][j] not in [0,1]:
            if answer[i][j-1] == 0:
                answer[i][j] = 1
            else:
                answer[i][j] = 0
print(answer)  

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


№1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [7]:
import numpy as np

answer = np.arange(25).reshape(5,5)
for i in range(1, 5):
    answer[i] = answer[0]
print(answer)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


№1.3.3

Создать массив 3x3x3 со случайными значениями.

In [12]:
import numpy as np

answer = np.random.random((3, 3, 3))
print(answer)

[[[0.03346914 0.85165395 0.05150813]
  [0.62942921 0.00251247 0.38266876]
  [0.14318301 0.90130916 0.46661131]]

 [[0.84017606 0.26175339 0.30402398]
  [0.7756719  0.04783608 0.1228234 ]
  [0.24912673 0.1881382  0.57247338]]

 [[0.53569536 0.69451368 0.51318091]
  [0.87168896 0.20977953 0.61466392]
  [0.24371191 0.2292021  0.19521402]]]


№1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [15]:
import numpy as np

answer = np.arange(25).reshape(5,5)
for i in range(len(answer)):
    for j in range(len(answer[i])):
        if i == 0 or i == len(answer) - 1:
            answer[i][j] = 1
        elif j == 0 or j == len(answer[i]) - 1:
            answer[i][j] = 1
        else:
            answer[i][j] = 0
print(answer)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


№1.3.5

Создайте массив и отсортируйте его по убыванию.

In [16]:
import numpy as np

answer = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.sort(answer)
print(answer[::-1])

[10  9  8  7  6  5  4  3  2  1]


№1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [20]:
import numpy as np

answer = np.arange(25).reshape(5,5)
print(answer.shape)
print(answer.size)
print(answer.ndim)

(5, 5)
25
2


№2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [23]:
import numpy as np
import pandas as pd

a = pd.Series([1, 2, 3, 4])
b = pd.Series([5, 6, 7, 8])
print(np.sqrt(((a - b) ** 2).sum()))

8.0


№2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [35]:
import pandas as pd

# Используем "raw" версию ссылки
url = "https://raw.githubusercontent.com/akmand/datasets/main/australian.csv"

df = pd.read_csv(url)
df.head(8)


A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1   65  168   2   4   4  39   0   0    1    1    2   32  161          0
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1          1
4   1   44  134   2   6   4  46   1   1   15    0    2   18   68          1
5   0    4   20   2   8   8  37   1   1    3    0    2   32    1          1
6   1   16  119   2   3   4   4   0   0    1    0    2   18   50          0
7   0  330   94   2  11   8  66   1   1    7    0    2   12  120          1

№2.3.3

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [34]:
import pandas as pd

# Используем "raw" версию ссылки
url = "https://raw.githubusercontent.com/akmand/datasets/main/australian.csv"

df = pd.read_csv(url)
df.head(2) # первые строчки

df.tail(3) # последние строки

df.shape # размерность

df.describe() # статистика

A1          A2          A3          A4          A5          A6  \
count  690.000000  690.000000  690.000000  690.000000  690.000000  690.000000   
mean     0.678261  148.686957   82.682609    1.766667    7.372464    4.692754   
std      0.467482   92.932052   58.792636    0.430063    3.683265    1.992316   
min      0.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      0.000000   72.000000   33.000000    2.000000    4.000000    4.000000   
50%      1.000000  134.500000   70.000000    2.000000    8.000000    4.000000   
75%      1.000000  219.750000  125.750000    2.000000   10.000000    5.000000   
max      1.000000  350.000000  215.000000    3.000000   14.000000    9.000000   

               A7          A8          A9         A10         A11         A12  \
count  690.000000  690.000000  690.000000  690.000000  690.000000  690.000000   
mean    37.147826    0.523188    0.427536    3.298551    0.457971    1.928986   
std     36.328826    0.499824    0.495080    4.034413    0.498592    0.298813   
min      1.000000    0.000000    0.000000    1.000000    0.000000    1.000000   
25%      5.000000    0.000000    0.000000    1.000000    0.000000    2.000000   
50%     26.000000    1.000000    0.000000    1.000000    0.000000    2.000000   
75%     61.000000    1.000000    1.000000    4.000000    1.000000    2.000000   
max    132.000000    1.000000    1.000000   23.000000    1.000000    3.000000   

              A13         A14   A15_class  
count  690.000000  690.000000  690.000000  
mean    58.797101   55.143478    0.444928  
std     46.150187   72.695049    0.497318  
min      1.000000    1.000000    0.000000  
25%     24.000000    1.000000    0.000000  
50%     53.000000    6.000000    0.000000  
75%     95.000000  107.750000    1.000000  
max    171.000000  240.000000    1.000000

In [36]:
import pandas as pd

# Используем "raw" версию ссылки
url = "https://raw.githubusercontent.com/akmand/datasets/main/australian.csv"

df = pd.read_csv(url)
df.loc[[1, 2, 3]]

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1          1

In [37]:
import pandas as pd

# Используем "raw" версию ссылки
url = "https://raw.githubusercontent.com/akmand/datasets/main/australian.csv"

df = pd.read_csv(url)
new_df = df.loc[df["A2"] > 100]
new_df.head()

A1   A2   A3  A4  A5  A6   A7  A8  A9  A10  A11  A12  A13  A14  A15_class
2    0  142   52   1   4   4   31   0   0    1    1    2   98    1          0
7    0  330   94   2  11   8   66   1   1    7    0    2   12  120          1
8    1  126   33   1   2   8   65   0   0    1    0    2   61  117          0
9    0  315  125   2   4   8  100   1   1    4    1    2   32   36          0
10   1  183   52   2  14   8   81   1   1    5    1    2   89  144          1

№3.3.2

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [51]:
import pandas as pd
import sklearn.preprocessing as sk

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)
min_max_scaler = sk.MinMaxScaler()
standart_scaler = sk.StandardScaler()
df["sepal_length_cm"] = min_max_scaler.fit_transform(df[["sepal_length_cm"]])
df["sepal_width_cm"] = standart_scaler.fit_transform(df[["sepal_width_cm"]])
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa